### ISSUE TITLE
Cannot get data from provided structure

### ISSUE THREAD

**Issue by XaviPadern** [RobThree/NEnvoy#1]
I'm not able to get fields inside the structure provided in the library. For example, if I get the production this way:

ProductionData production = client.GetProductionAsync().Result;

I don't know how to get the production/consumption value:

production.Consumption.ElementAt(0).???

how can I get for example production[0].WattsNow or similar? thanks a lot for your help!

**Comment by RobThree** [comment]
First of all: You should be [awaiting](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/await) the `GetProductionAsync()` call.

Then, the result of the `GetProductionAsync()` is [`ProductionData`](https://github.com/RobThree/NEnvoy/blob/cb0c52feb579a6cd81683aa33941f87315c234ba/NEnvoy/Models/Production.cs#L4) which contains 3 IEnumerable&lt;T&gt;'s: `Production`, `Consumption` and `Storage`, all of basetype [`ProductionRecord`](https://github.com/RobThree/NEnvoy/blob/cb0c52feb579a6cd81683aa33941f87315c234ba/NEnvoy/Models/ProductionRecord.cs#L10). The actual types may be either: [`Battery`](https://github.com/RobThree/NEnvoy/blob/cb0c52feb579a6cd81683aa33941f87315c234ba/NEnvoy/Models/Battery.cs#L5), [`EIM`](https://github.com/RobThree/NEnvoy/blob/cb0c52feb579a6cd81683aa33941f87315c234ba/NEnvoy/Models/EIM.cs#L5) or [`Inverter`](https://github.com/RobThree/NEnvoy/blob/cb0c52feb579a6cd81683aa33941f87315c234ba/NEnvoy/Models/Inverters.cs#L5).

You could then do something like:

```c#
var production = await client.GetProductionAsync().ConfigureAwait(false);

PrintProductionRecords(production.Consumption);
PrintProductionRecords(production.Production);
PrintProductionRecords(production.Storage);
```
With the following helper methods:
```c#
    private static void PrintProductionRecords(IEnumerable<ProductionRecord> pr) {
        foreach (var r in pr)
            PrintProductionRecord(r);
    }

    private static void PrintProductionRecord(ProductionRecord r) {
        switch (r) {
            case Battery b:
                Console.WriteLine("Battery: {0}", b.State);
                break;
            case EIM e:
                Console.WriteLine("EIM: {0}", e.CapacitiveReactantEnergyLifetime);
                break;
            case Inverters i:
                Console.WriteLine("Inverter: {0}", i.WattHoursNow);
                break;
        }
    }
```
Above is, clearly, just an example showing accessing only 1 single "random" property of the `Battery`, `EIM` and `Inverters` objects. But it should give you an idea on how to access the EIM/Battery/Inverters models in the ProductionData record.

**Comment by XaviPadern** [comment]
Thanks Rob! I'm now able to access them
